//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projet2
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssociationPreferenceJour
    {
        public Nullable<System.DateTime> DateChoix { get; set; }
        public Nullable<System.DateTime> DateRenoncementChoix { get; set; }
        public Nullable<System.TimeSpan> HeureDebutDispo { get; set; }
        public Nullable<System.TimeSpan> HeureFinDispo { get; set; }
        public Nullable<int> NumCompte { get; set; }
        public Nullable<int> IdJour { get; set; }
        public int Idapj { get; set; }
    
        public virtual Jour Jour { get; set; }
        public virtual Utilisateur Utilisateur { get; set; }
    }
}
