//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projet2
{
    using System;
    using System.Collections.Generic;
    
    public partial class BesoinMateriel
    {
        public Nullable<int> QuantiteMateriel { get; set; }
        public Nullable<int> IdTypeMateriel { get; set; }
        public Nullable<int> IdTypeAide { get; set; }
        public int IdBM { get; set; }
    
        public virtual TypeAide TypeAide { get; set; }
        public virtual TypeMateriel TypeMateriel { get; set; }
    }
}
