//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projet2
{
    using System;
    using System.Collections.Generic;
    
    public partial class DemandeAide
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DemandeAide()
        {
            this.DemandeMateriel = new HashSet<DemandeMateriel>();
            this.Repondre = new HashSet<Repondre>();
        }
    
        public int NumDemandeAide { get; set; }
        public string Description { get; set; }
        public string DateDepotDemande { get; set; }
        public string NoteBeneficiaire { get; set; }
        public string NoteVolontaire { get; set; }
        public string DateAnnulationDemande { get; set; }
        public string DateTraitement { get; set; }
        public Nullable<int> NumCompte { get; set; }
        public Nullable<int> IdTypeAide { get; set; }
    
        public virtual TypeAide TypeAide { get; set; }
        public virtual Utilisateur Utilisateur { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DemandeMateriel> DemandeMateriel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Repondre> Repondre { get; set; }
    }
}
