//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projet2
{
    using System;
    using System.Collections.Generic;
    
    public partial class TypeMateriel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TypeMateriel()
        {
            this.BesoinMateriel = new HashSet<BesoinMateriel>();
            this.DemandeMateriel = new HashSet<DemandeMateriel>();
        }
    
        public int IdTypeMateriel { get; set; }
        public string LibelleTypeMateriel { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BesoinMateriel> BesoinMateriel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DemandeMateriel> DemandeMateriel { get; set; }
    }
}
